[[0, 0, 0], 1.0, {"submitted": 1621136669.2162907, "started": 1621136669.2162907, "finished": 1621136669.2392232}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 1], 1.0, {"submitted": 1621136669.2422457, "started": 1621136669.2422457, "finished": 1621136669.2631862}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 2], 1.0, {"submitted": 1621136669.2661877, "started": 1621136669.2661877, "finished": 1621136669.3249934}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 3], 1.0, {"submitted": 1621136669.3279846, "started": 1621136669.3279846, "finished": 1621136669.3439422}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 4], 1.0, {"submitted": 1621136669.3459492, "started": 1621136669.3459492, "finished": 1621136669.3638897}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 5], 1.0, {"submitted": 1621136669.3658834, "started": 1621136669.3658834, "finished": 1621136669.384833}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 6], 1.0, {"submitted": 1621136669.3868275, "started": 1621136669.3868275, "finished": 1621136669.403782}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 7], 1.0, {"submitted": 1621136669.4057767, "started": 1621136669.4067743, "finished": 1621136669.4247267}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 8], 1.0, {"submitted": 1621136669.4267542, "started": 1621136669.4267542, "finished": 1621136669.4416807}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 9], 1.0, {"submitted": 1621136669.4436986, "started": 1621136669.4436986, "finished": 1621136669.4596334}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 10], 1.0, {"submitted": 1621136669.4616275, "started": 1621136669.4626238, "finished": 1621136669.478583}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 11], 1.0, {"submitted": 1621136669.4805772, "started": 1621136669.4805772, "finished": 1621136669.5048215}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 12], 1.0, {"submitted": 1621136669.506817, "started": 1621136669.5078144, "finished": 1621136669.5227754}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 13], 1.0, {"submitted": 1621136669.5257666, "started": 1621136669.5257666, "finished": 1621136669.542721}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 14], 1.0, {"submitted": 1621136669.5457408, "started": 1621136669.5457408, "finished": 1621136669.5646622}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 15], 1.0, {"submitted": 1621136669.567655, "started": 1621136669.567655, "finished": 1621136669.5816174}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 16], 1.0, {"submitted": 1621136669.5846088, "started": 1621136669.5846088, "finished": 1621136669.600566}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 17], 1.0, {"submitted": 1621136669.6027184, "started": 1621136669.6027184, "finished": 1621136669.6176786}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 18], 1.0, {"submitted": 1621136669.620697, "started": 1621136669.620697, "finished": 1621136669.6366608}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 19], 1.0, {"submitted": 1621136669.6396194, "started": 1621136669.6396194, "finished": 1621136669.657572}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 20], 1.0, {"submitted": 1621136669.6605883, "started": 1621136669.6605883, "finished": 1621136669.6785166}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 21], 1.0, {"submitted": 1621136669.6815388, "started": 1621136669.6815388, "finished": 1621136669.6955092}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 22], 1.0, {"submitted": 1621136669.697465, "started": 1621136669.6984627, "finished": 1621136669.713454}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 23], 1.0, {"submitted": 1621136669.7164147, "started": 1621136669.7174115, "finished": 1621136669.7313745}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 24], 1.0, {"submitted": 1621136669.799194, "started": 1621136669.799194, "finished": 1621136669.8171442}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 25], 1.0, {"submitted": 1621136669.8201365, "started": 1621136669.8201365, "finished": 1621136669.834101}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 0, 26], 1.0, {"submitted": 1621136669.9108932, "started": 1621136669.9108932, "finished": 1621136669.9278498}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 0], 3.0, {"submitted": 1621136669.9956875, "started": 1621136669.9956875, "finished": 1621136670.0136209}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 1], 3.0, {"submitted": 1621136670.0854588, "started": 1621136670.0854588, "finished": 1621136670.0993915}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 2], 3.0, {"submitted": 1621136670.167237, "started": 1621136670.1682057, "finished": 1621136670.1811728}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 3], 3.0, {"submitted": 1621136670.2499871, "started": 1621136670.2499871, "finished": 1621136670.264986}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 4], 3.0, {"submitted": 1621136670.3317773, "started": 1621136670.332767, "finished": 1621136670.3467276}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 5], 3.0, {"submitted": 1621136670.4135487, "started": 1621136670.4135487, "finished": 1621136670.430569}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 6], 3.0, {"submitted": 1621136670.498322, "started": 1621136670.498322, "finished": 1621136670.5162742}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 7], 3.0, {"submitted": 1621136670.5820987, "started": 1621136670.583096, "finished": 1621136670.5990534}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 1, 8], 3.0, {"submitted": 1621136670.6654146, "started": 1621136670.6664119, "finished": 1621136670.679378}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 2, 0], 9.0, {"submitted": 1621136670.7456262, "started": 1621136670.7456262, "finished": 1621136670.7595894}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 2, 1], 9.0, {"submitted": 1621136670.8264565, "started": 1621136670.8264565, "finished": 1621136670.8434355}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 2, 2], 9.0, {"submitted": 1621136670.9112298, "started": 1621136670.9122272, "finished": 1621136670.9291832}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
[[0, 3, 0], 27.0, {"submitted": 1621136670.931188, "started": 1621136670.9321737, "finished": 1621136670.9471648}, null, "Traceback (most recent call last):\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\hpbandster\\core\\worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"C:\\Users\\ameof\\Documents\\school\\independent study\\melee bot\\tune.py\", line 128, in compute\n    max_episode_timesteps=self.max_episode_timesteps\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\execution\\runner.py\", line 178, in __init__\n    self.agent = Agent.create(agent=agent, environment=environment)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 112, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 131, in create\n    return Agent.create(agent=agent, environment=environment, **kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\agent.py\", line 98, in create\n    agent = agent(**kwargs)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\agents\\tensorforce.py\", line 429, in __init__\n    config=self.config, saver=saver, summarizer=summarizer\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\models\\tensorforce.py\", line 517, in __init__\n    values_spec=values_spec, min_capacity=min_capacity\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 483, in submodule\n    name=name, module=module, modules=modules, default_module=default_module, **kwargs\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\core\\module.py\", line 381, in get_module_class_and_args\n    util.deep_disjoint_update(target=kwargs, source=module)\n  File \"C:\\Users\\ameof\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\tensorforce\\util.py\", line 144, in deep_disjoint_update\n    name='spec', argument=key, value1=target[key], value2=value\ntensorforce.exception.TensorforceError: Spec mismatch for argument min_capacity: 1 != None.\n"]
